"""Hermetic tests for lib/handoff.py.

generate_handoff writes under DATA_DIR (computed at module import). We monkeypatch
handoff.DATA_DIR to a temp dir so nothing lands in the live /data/clanker store,
then drive it against real temp git repos. Key contract: it captures branch /
last-commit / dirty-file info on a repo, and is FAIL-OPEN on a non-git dir (never
raises — a session end must always produce a handoff).
"""
import os
import subprocess
import sys

import pytest

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_REPO, "lib"))
import handoff  # noqa: E402


def _git(cwd, *args):
    subprocess.run(["git", "-C", cwd, *args], check=True, capture_output=True, text=True)


@pytest.fixture
def data_dir(tmp_path, monkeypatch):
    d = tmp_path / "data"
    d.mkdir()
    monkeypatch.setattr(handoff, "DATA_DIR", str(d))
    return d


def _commit_repo(path):
    path.mkdir()
    _git(str(path), "init", "-q", "-b", "main")
    _git(str(path), "config", "user.email", "t@t")
    _git(str(path), "config", "user.name", "t")
    (path / "f.txt").write_text("x")
    _git(str(path), "add", "-A")
    _git(str(path), "commit", "-qm", "initial commit")


def test_handoff_on_git_repo(tmp_path, data_dir):
    repo = tmp_path / "repo"
    _commit_repo(repo)
    (repo / "dirty.txt").write_text("y")  # one untracked file -> dirty count 1

    path = handoff.generate_handoff("abcd1234efgh5678", "myproj", str(repo))
    assert os.path.exists(path)
    assert str(data_dir) in path                       # under the redirected store
    assert path.endswith("myproj-handoff.md")

    text = open(path).read()
    assert "# Handoff: myproj" in text
    assert "**Branch:** main" in text
    assert "**Last commit:**" in text
    assert "initial commit" in text
    assert "**Session:** abcd1234" in text             # session_id[:8]
    assert "**Dirty files:** 1" in text
    assert "Auto-generated by clanker" in text


def test_handoff_clean_repo_omits_dirty_line(tmp_path, data_dir):
    repo = tmp_path / "clean"
    _commit_repo(repo)
    text = open(handoff.generate_handoff("sess0000abcd", "clean", str(repo))).read()
    assert "**Branch:** main" in text
    assert "**Dirty files:**" not in text              # nothing uncommitted


def test_handoff_non_git_dir_fail_open(tmp_path, data_dir):
    plain = tmp_path / "plain"
    plain.mkdir()
    # Must not raise even though there is no .git — fail-open by contract.
    path = handoff.generate_handoff("sessid00", "proj2", str(plain))
    text = open(path).read()
    assert "# Handoff: proj2" in text
    assert "**Session:** sessid00" in text
    assert "**Branch:**" not in text                   # git section skipped


def test_handoff_git_repo_without_commits_does_not_raise(tmp_path, data_dir):
    repo = tmp_path / "empty"
    repo.mkdir()
    _git(str(repo), "init", "-q", "-b", "main")        # no commits -> git log fails
    path = handoff.generate_handoff("nnnnnnnnnnnn", "p3", str(repo))
    text = open(path).read()
    # the git block raises internally and is swallowed; the doc still renders.
    assert "# Handoff: p3" in text
    assert "**Session:** nnnnnnnn" in text
    assert "**Branch:**" not in text
