"""Session handoffs — auto-generate structured handoff on session end."""

import json
import os
import subprocess
from datetime import datetime

DATA_DIR = os.environ.get("CLANKER_DATA", "/data/clanker")


def generate_handoff(session_id, project, cwd, transcript_path=None):
    """Generate a structured handoff document for the next session."""
    sections = []

    # 1. Git state
    if os.path.isdir(os.path.join(cwd, ".git")):
        try:
            branch = subprocess.check_output(
                ["git", "-C", cwd, "branch", "--show-current"],
                stderr=subprocess.DEVNULL, text=True
            ).strip()
            last_commit = subprocess.check_output(
                ["git", "-C", cwd, "log", "--oneline", "-1"],
                stderr=subprocess.DEVNULL, text=True
            ).strip()
            dirty = subprocess.check_output(
                ["git", "-C", cwd, "status", "--short"],
                stderr=subprocess.DEVNULL, text=True
            ).strip()
            sections.append(f"**Branch:** {branch}")
            sections.append(f"**Last commit:** {last_commit}")
            if dirty:
                sections.append(f"**Dirty files:** {len(dirty.split(chr(10)))}")
        except:
            pass

    # 2. Session metadata
    sections.append(f"**Session:** {session_id[:8]}")
    sections.append(f"**Time:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")

    # 3. Build handoff markdown
    handoff = f"# Handoff: {project}\n\n"
    handoff += "\n".join(sections) + "\n"
    handoff += "\n*Auto-generated by clanker. The next session will see this in its briefing.*\n"

    # Save
    handoff_path = os.path.join(DATA_DIR, "wiki", "projects", f"{project}-handoff.md")
    os.makedirs(os.path.dirname(handoff_path), exist_ok=True)
    with open(handoff_path, "w") as f:
        f.write(handoff)

    return handoff_path
