"""Plugin architecture — drop-in analyzers and health checks."""

import os
import subprocess
import json
from datetime import datetime

DATA_DIR = os.environ.get("CLANKER_DATA", "/data/clanker")
PLUGINS_DIR = os.path.join(DATA_DIR, "plugins")


def ensure_plugin_dirs():
    """Create plugin directories."""
    for subdir in ["analyzers", "health-checks"]:
        os.makedirs(os.path.join(PLUGINS_DIR, subdir), exist_ok=True)


def discover_plugins(plugin_type="analyzers"):
    """Find all plugins of a given type."""
    plugin_dir = os.path.join(PLUGINS_DIR, plugin_type)
    if not os.path.isdir(plugin_dir):
        return []

    plugins = []
    for f in sorted(os.listdir(plugin_dir)):
        path = os.path.join(plugin_dir, f)
        if os.access(path, os.X_OK) or f.endswith(".py") or f.endswith(".sh"):
            plugins.append({"name": f, "path": path, "type": plugin_type})
    return plugins


def run_plugin(plugin, stdin_data=None, timeout=60):
    """Run a plugin and capture output.

    Plugins follow the Unix convention:
    - Read JSONL from stdin
    - Write findings to stdout (JSONL or text)
    - Exit 0 on success, non-zero on failure
    """
    cmd = plugin["path"]
    if cmd.endswith(".py"):
        cmd = f"python3 {cmd}"
    elif cmd.endswith(".sh"):
        cmd = f"bash {cmd}"

    try:
        proc = subprocess.run(
            cmd, shell=True,
            input=stdin_data,
            capture_output=True, text=True,
            timeout=timeout
        )
        return {
            "name": plugin["name"],
            "exit_code": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
        }
    except subprocess.TimeoutExpired:
        return {
            "name": plugin["name"],
            "exit_code": -1,
            "stdout": "",
            "stderr": f"Timed out after {timeout}s",
        }


def scaffold_watchdog(name: str, kind: str = "config-drift",
                      out_dir: str | None = None) -> str:
    """Scaffold a new health-check 'drift watchdog' plugin.

    Class-of-bug fix from eigenstateresearch Session 7 (2026-04-18):
    every config that encodes an external-world fact (city → ICAO
    map, API contracts, etc.) needs a paired watchdog plugin to alert
    on drift. Hand-writing each was 200 lines of boilerplate; this
    generator emits a runnable template.

    Parameters
    ----------
    name : short slug like 'station-drift', 'forecast-bias', 'wu-schema'.
        The plugin will be created as `pwb-<name>.py` (or `<name>.py` if
        no project prefix is appropriate).
    kind : currently 'config-drift' (compares a local dict literal
        against a fetched external source). Future: 'api-contract',
        'sql-schema', 'param-bounds'.
    out_dir : where to write. Defaults to the project's clanker_plugins
        dir if running inside a project, else /data/clanker/plugins/health-checks.

    Returns the absolute path of the created plugin.
    """
    if not name or not name.replace("-", "").replace("_", "").isalnum():
        raise ValueError(f"invalid name: {name!r}")
    target_dir = out_dir or os.path.join(PLUGINS_DIR, "health-checks")
    os.makedirs(target_dir, exist_ok=True)
    fname = name if name.endswith(".py") else f"{name}.py"
    target = os.path.join(target_dir, fname)
    if os.path.exists(target):
        raise FileExistsError(f"{target} already exists — refusing to overwrite")

    template = _watchdog_template(name=name, kind=kind)
    with open(target, "w") as f:
        f.write(template)
    os.chmod(target, 0o755)
    return target


def _watchdog_template(name: str, kind: str) -> str:
    """The boilerplate every drift watchdog needs. Operator fills in
    LOCAL_SOURCE, REMOTE_FETCHER, COMPARE_FN."""
    return f'''#!/usr/bin/env python3
"""{name}: drift watchdog ({kind}).

Generated by `clanker new-watchdog`. Fill in LOCAL_SOURCE, REMOTE_FETCH,
and COMPARE to turn this scaffold into a live alert.

Pattern (from eigenstateresearch Session 7 audit):
  Every config that encodes a fact about the outside world needs a
  daily/15-min check that the fact still matches reality. Plugin output:

    {{"status": "ok"|"warning"|"critical", "message": "...", "data": {{...}}}}

  Exit code: 0 ok, 1 warning, 2 critical.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request


# ── Step 1: identify the LOCAL fact you're watching ────────────────────────
def load_local() -> dict:
    """Return the local config / map / value to compare. Example:
        with open("/path/to/config.json") as f:
            return json.load(f)
    """
    raise NotImplementedError("fill in load_local() with your local source")


# ── Step 2: fetch the REMOTE truth ─────────────────────────────────────────
def fetch_remote() -> dict:
    """Hit the external system + return what the local fact SHOULD be.
    Use a 30s timeout + 2 retries; refuse to silently pass on network
    failure (a watchdog that can't run isn't a watchdog).
    """
    raise NotImplementedError("fill in fetch_remote() with your remote source")


# ── Step 3: compare + return drift list ────────────────────────────────────
def compare(local: dict, remote: dict) -> list[dict]:
    """Return list of mismatches. Empty list = no drift."""
    raise NotImplementedError("fill in compare() with your equality logic")


def main() -> int:
    try:
        local = load_local()
        remote = fetch_remote()
    except NotImplementedError as e:
        print(json.dumps({{
            "status": "critical",
            "message": f"watchdog scaffold not filled in: {{e}}",
            "data": {{}},
        }}))
        return 2
    except Exception as e:
        print(json.dumps({{
            "status": "critical",
            "message": f"watchdog setup failed: {{type(e).__name__}}: {{e}}",
            "data": {{}},
        }}))
        return 2

    drifts = compare(local, remote)
    data = {{"n_drifts": len(drifts), "drifts": drifts[:15]}}

    if not drifts:
        print(json.dumps({{
            "status": "ok",
            "message": "no drift detected",
            "data": data,
        }}))
        return 0
    if len(drifts) == 1:
        print(json.dumps({{
            "status": "warning",
            "message": f"1 drift: {{drifts[0]}}",
            "data": data,
        }}))
        return 1
    print(json.dumps({{
        "status": "critical",
        "message": f"{{len(drifts)}} drifts detected",
        "data": data,
    }}))
    return 2


if __name__ == "__main__":
    sys.exit(main())
'''


def run_all_analyzers(session_data=None):
    """Run all analyzer plugins against session data."""
    plugins = discover_plugins("analyzers")
    if not plugins:
        print("No analyzer plugins found.")
        print(f"Drop scripts in: {os.path.join(PLUGINS_DIR, 'analyzers')}/")
        print("Interface: read JSONL from stdin, write findings to stdout")
        return []

    results = []
    for p in plugins:
        print(f"Running analyzer: {p['name']}")
        result = run_plugin(p, stdin_data=session_data)
        results.append(result)
        if result["stdout"]:
            print(result["stdout"])
        if result["stderr"]:
            print(f"  STDERR: {result['stderr']}", end="")
    return results


def run_all_health_checks():
    """Run all health check plugins."""
    plugins = discover_plugins("health-checks")
    if not plugins:
        return []

    results = []
    for p in plugins:
        result = run_plugin(p, timeout=30)
        results.append(result)
    return results


def list_plugins():
    """List all installed plugins."""
    ensure_plugin_dirs()
    print("=== Clanker Plugins ===\n")
    for ptype in ["analyzers", "health-checks"]:
        plugins = discover_plugins(ptype)
        print(f"{ptype}/ ({len(plugins)} plugins)")
        if plugins:
            for p in plugins:
                print(f"  {p['name']}")
        else:
            print(f"  (empty — drop scripts here: {os.path.join(PLUGINS_DIR, ptype)}/)")
        print()
